"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 10:59:39.426665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decoration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Enum('cover', 'about', 'projects', 'work', name='decorationpage', native_enum=False, length=32), nullable=False),
    sa.Column('src', sa.String(length=500), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('rotate', sa.Float(), server_default='0', nullable=False),
    sa.Column('scale', sa.Float(), server_default='1', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('years', sa.String(length=100), nullable=False),
    sa.Column('org', sa.String(length=300), nullable=False),
    sa.Column('degree', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.Enum('Code', 'Youtube', 'Palette', 'Gamepad2', 'Cat', 'Scissors', name='hobbyicon', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Unicode(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=False),
    sa.Column('photo_hero', sa.String(length=500), nullable=False),
    sa.Column('photo_about', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('long_bio', sa.Text(), nullable=False),
    sa.Column('dob', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rated_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('coding', 'frameworks', name='ratedskillcategory', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Enum('Beginner', 'Intermediate', 'Advanced', 'Mastered', name='skilllevel', native_enum=False, length=32), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('software', 'design', 'traits', name='skilltagcategory', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Enum('github', 'discord', 'kofi', name='socialkey', native_enum=False, length=32), nullable=False),
    sa.Column('href', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supporter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('kofi', 'manual', name='supportersource', native_enum=False, length=32), nullable=False),
    sa.Column('kofi_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kofi_transaction_id')
    )
    op.create_index(op.f('ix_supporter_created_at'), 'supporter', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supporter_created_at'), table_name='supporter')
    op.drop_table('supporter')
    op.drop_table('social_link')
    op.drop_table('skill_tag')
    op.drop_table('rated_skill')
    op.drop_table('project')
    op.drop_table('personal')
    op.drop_table('media')
    op.drop_table('language')
    op.drop_table('hobby')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('decoration')
    op.drop_table('activity')
    # ### end Alembic commands ###
