"""project github stars

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22 14:45:37.830259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_stars', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('github_stars_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'github_stars_updated_at')
    op.drop_column('project', 'github_stars')
    # ### end Alembic commands ###
